development:
  password: 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
  theme_id: "115652034730"
  store: jungleflorist.myshopify.com
  ignore_files:
    - config/settings_data.json
    - "*.swp"
    - "*~"